FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1
ENV TEMP=0.1
ENV MAX_CTX_LENGTH=131072

EXPOSE 7860

CMD ["python", "main.py"]